name: Linter-check
on: push
jobs:
  make-lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: make install
      - name: Run Linter
        run: make lint